version: '3'

services:
  web:
    container_name: web-demo
    image: daniel0318pisces/my_repo:latest
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres
      - redis
    environment:
      - REDIS_HOST=redis

  my-postgres:
    container_name: db-demo
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword

  redis:
    container_name: cache-demo
    image: redis:latest
    ports:
      - "6379:6379"
